### PR TITLE
eeprom_crc: add eeprom functions for consistency

### PR DESCRIPTION
**Pull request by javierfileiv**
Added funtions to verify consistency on eeprom memory

### CODE REVIEW

**Comment by ermtl** [comment]
Hi, looks like our change conflict, for we changed the same parts. 
Also, you made a .h file in the same directory as the main one for just 1 function. That's not the way it's generally done in Arduino.
Another point is I would like to have a CRC just for the struct and not the whole EEPROM, as it then becomes possible to have a second copy of the data and if the first fails, the second is used, but for that, each must have it's own CRC.

**Comment by javierfileiv** [comment]
It's ok... I don't feel comfortable with this environment. You can close this PR :)

**Comment by Blimpyway** [comment]
If an unlikely event as eeprom writing has failed I would suspect something is really wrong with the machine and avoid use it anymore.   I mean if you assume it happened twice then it is really, really time to dump it.

**Comment by ermtl** [comment]
@javierfileiv  Thanks for the attempt and sorry to learn that you don't want to work within the Arduino development system.

FYI, here is the library I'll be using
https://github.com/bakercp/CRC32

**Pull request closed without merging**
