### PR TITLE
CI using GitHub Workflows

### PR DESCRIPTION
**Pull request by mattd3v**
For issue #3 I have added a CI workflow to setup the Arduino environment and compile the source. However, I commented out the jm_Wire define statement because, even locally, I have not been able to build with it included.

### CODE REVIEW

**Comment by frippe75** [comment]
I know Vlad designing the PCB is hosting both the Arduino Nano as well as the ESP32. Possible to compile fo both? @ermtl something you're interested in?

Also why not add the workflow for PR's as well so that accepted PR's is prevalidated somewhat.

**Comment by mattd3v** [comment]
Agreed, I will add run on PRs, if it’s something we want? As for ESP32, it shouldn’t be hard.

I also have a working GitLab CI configuration, which sets up the Arduino environment using a shell script. However with the setup-arduino-cli Action, the GitHub Workflow is simpler.

**Comment by karx** [comment]
@mattd3v regarding building for ESP32, I see there are a few components of the code, like timers and stepper motor control that would have to be written for the esp32 architecture. 

Where are we on that, and how can I help.

**Comment by karx** [comment]
@mattd3v You've deleted your fork?
1
any particular reason why?

**Pull request closed without merging**
